namespace RPG_Harness.Services;

/// <summary>
/// Английские названия клеток листа навыков и английские основы слов для подбора иконки.
/// Слова добавляются к русским всегда (навык могут назвать на любом языке), названия — только в английском интерфейсе.
/// </summary>
public static partial class SkillIcons
{
    private static Dictionary<string, (string Title, string[] Kw)> MetaEn => Genre.Pick(FantasyEn, CyberEn, ModernEn);

    private static readonly Dictionary<string, (string Title, string[] Kw)> FantasyEn = new(StringComparer.OrdinalIgnoreCase)
    {
        ["slash"] = ("blade strike", ["strike", "slash", "cleave", "blade", "lunge", "stab", "attack", "sword", "flurry", "whirlwind"]),
        ["fire"] = ("fire", ["fire", "flame", "blaze", "burning", "inferno", "fireball", "meteor", "pyro", "scorch"]),
        ["frost"] = ("ice", ["ice", "icy", "frost", "cold", "chill", "snow", "blizzard", "glacial"]),
        ["lightning"] = ("lightning", ["lightning", "thunder", "shock", "electric", "storm", "spark", "bolt"]),
        ["wind"] = ("wind", ["wind", "gust", "tornado", "whirl", "air", "gale", "hurricane", "cyclone"]),
        ["earth"] = ("earth", ["earth", "stone", "rock", "spike", "quake", "boulder", "avalanche", "tremor"]),
        ["shadow"] = ("darkness", ["dark", "shadow", "gloom", "abyss", "void", "necro", "soul"]),
        ["holy"] = ("light", ["light", "holy", "sacred", "sun", "divine", "radian", "smite", "celestial"]),
        ["heal"] = ("healing", ["heal", "cure", "mend", "restor", "bandage", "health", "recover"]),
        ["water"] = ("water and cleansing", ["water", "wave", "cleans", "purif", "tide", "flood", "stream"]),
        ["revive"] = ("resurrection", ["resurrect", "reviv", "rebirth", "phoenix", "spirit", "angel"]),
        ["barrier"] = ("barrier", ["barrier", "shield", "aegis", "sphere", "dome", "ward"]),
        ["might"] = ("might and rage", ["might", "rage", "power", "berserk", "fury", "battle cry", "warcry", "inspir", "strength"]),
        ["haste"] = ("haste", ["haste", "speed", "dash", "sprint", "swift", "charge", "dodge", "leap", "jump"]),
        ["stealth"] = ("stealth", ["stealth", "invisib", "hide", "hidden", "disguise", "vanish", "ambush", "sneak"]),
        ["guard"] = ("defense", ["defen", "block", "parry", "guard", "protect", "cover", "taunt", "provok", "stance"]),
        ["poison"] = ("poison", ["poison", "venom", "toxin", "toxic", "plague", "miasma", "acid"]),
        ["bleed"] = ("bleeding", ["bleed", "blood", "wound", "rend", "vampir"]),
        ["burn"] = ("burning", ["ignite", "burn", "smolder", "napalm"]),
        ["stun"] = ("stun", ["stun", "daze", "concuss", "stagger"]),
        ["sleep"] = ("sleep", ["sleep", "slumber", "drowse", "lullaby", "dream"]),
        ["fear"] = ("fear", ["fear", "terror", "horror", "intimidat", "frighten", "panic", "roar"]),
        ["blind"] = ("blindness", ["blind", "flash", "sand in the eyes"]),
        ["silence"] = ("silence", ["silenc", "mute", "hush"]),
        ["freeze"] = ("freeze", ["freez", "frozen", "encase in ice"]),
        ["sunder"] = ("armor break", ["sunder", "pierc", "shatter", "crush", "armor break", "rupture"]),
        ["weaken"] = ("weakness", ["weak", "enfeebl", "disarm", "feeble"]),
        ["slow"] = ("slow", ["slow", "sluggish", "quagmire", "mire", "time shackle"]),
        ["curse"] = ("curse", ["curse", "blight", "evil eye", "doom", "sorrow"]),
        ["hex"] = ("hex", ["hex", "voodoo", "needle", "doll", "mark", "brand"]),
        ["bind"] = ("bonds", ["chain", "shackle", "bind", "entangl", "net", "roots", "vine", "grapple", "snare"]),
        ["confuse"] = ("confusion", ["confus", "illusion", "hypno", "charm", "madness", "bewilder", "mirage"]),
        ["tome_fire"] = ("book of fire", ["book of fire", "grimoire of flame"]),
        ["tome_frost"] = ("book of ice", ["book of ice"]),
        ["tome_nature"] = ("book of nature", ["nature", "druid", "forest", "beast", "summon beast", "wild"]),
        ["tome_arcane"] = ("book of secrets", ["arcane", "magic", "rune", "enchant", "teleport", "portal", "identif", "analy", "detect"]),
        ["tome_holy"] = ("holy book", ["prayer", "bless", "vow"]),
        ["tome_death"] = ("book of the dead", ["dead", "undead", "raise", "summon skeleton"]),
        ["scroll_blood"] = ("blood scroll", ["bloody", "ritual", "sacrific"]),
        ["scroll_water"] = ("scroll of waters", ["scroll", "spell"]),
        ["ruby"] = ("ruby", ["ruby"]),
        ["sapphire"] = ("sapphire", ["sapphire"]),
        ["emerald"] = ("emerald", ["emerald"]),
        ["amethyst"] = ("amethyst", ["amethyst"]),
        ["diamond"] = ("diamond", ["diamond", "crystal"]),
        ["claw"] = ("claw", ["claw", "fang", "bite", "maul", "tear"]),
        ["horned_skull"] = ("horned skull", ["skull", "horned", "trophy"]),
        ["scales"] = ("dragon scale", ["scale", "dragon", "carapace"]),
        ["herbs"] = ("herbs", ["herb", "potion", "salve", "balm", "poultice"]),
        ["mushroom"] = ("mushroom", ["mushroom", "spore", "fung"]),
        ["vial"] = ("vial", ["vial", "alchem", "flask", "elixir", "bomb"]),
        ["ingot"] = ("ingot", ["ingot", "smith", "forge", "metal", "ore"]),
        ["fur"] = ("fur", ["fur", "hide", "pelt", "feather", "down"]),
        ["leather"] = ("leather", ["leather", "tanning"]),
        ["rope"] = ("rope", ["rope", "lasso", "lariat", "cord"]),
        ["crystals"] = ("crystals", ["crystal", "shard", "geode"]),
        ["potion_health"] = ("health potion", ["healing potion", "health potion"]),
        ["potion_mana"] = ("mana potion", ["mana", "meditat", "focus", "concentrat"]),
        ["potion_sun"] = ("sun potion", ["inspiration", "vigor"]),
        ["potion_poison"] = ("vial of poison", ["vial of poison"]),
        ["map"] = ("map", ["map", "track", "trail", "pathfind", "navigat", "scout"]),
        ["key"] = ("key", ["key", "lock", "pick", "burglar"]),
        ["gold"] = ("gold", ["gold", "trade", "bribe", "rob", "steal", "theft"]),
        ["amulet"] = ("amulet", ["amulet", "talisman", "aura"]),
    };

    private static readonly Dictionary<string, (string Title, string[] Kw)> ModernEn = new(StringComparer.OrdinalIgnoreCase)
    {
        ["slash"] = ("knife strike", ["knife", "cut", "strike", "shot", "burst", "shoot"]),
        ["fire"] = ("fire", ["molotov", "arson", "fire", "gasoline", "flamethrower"]),
        ["frost"] = ("cold", ["extinguisher", "cold", "ice", "frost"]),
        ["lightning"] = ("electroshock", ["stun gun", "electroshock", "current", "taser", "shock"]),
        ["wind"] = ("flashbang", ["flashbang", "sound", "deafen", "concuss"]),
        ["earth"] = ("explosion", ["explos", "grenade", "mine", "blast", "dynamite"]),
        ["shadow"] = ("hacking", ["hack", "laptop", "phone", "camera", "network"]),
        ["holy"] = ("aimed shot", ["aim", "sniper", "headshot", "precise"]),
        ["heal"] = ("bandaging", ["bandag", "first aid", "medkit", "heal", "medic"]),
        ["water"] = ("painkiller", ["painkiller", "come to", "antidote"]),
        ["revive"] = ("adrenaline", ["adrenaline", "defibrill", "resuscit", "back on their feet"]),
        ["barrier"] = ("cover", ["cover", "shield", "armor plate", "behind the car"]),
        ["might"] = ("rage", ["rage", "anger", "adrenaline", "strength"]),
        ["haste"] = ("dash", ["dash", "run", "roll", "speed", "sprint"]),
        ["stealth"] = ("stealth", ["stealth", "unnoticed", "shadow", "ambush", "disguise", "sneak"]),
        ["guard"] = ("defense", ["defen", "block", "cover", "take the hit"]),
        ["poison"] = ("gas and poison", ["gas", "tear gas", "pepper", "poison"]),
        ["bleed"] = ("bleeding", ["bleed", "blood", "wound"]),
        ["burn"] = ("burning", ["burn", "fire"]),
        ["stun"] = ("stun", ["stun", "knockout", "blow to the head"]),
        ["sleep"] = ("tranquilizer", ["tranquil", "sedat", "sleep"]),
        ["fear"] = ("intimidation", ["intimidat", "pressure", "panic", "threat"]),
        ["blind"] = ("blinding", ["blind", "flash", "flashlight", "sand"]),
        ["silence"] = ("jammer", ["jam", "radio", "comms"]),
        ["freeze"] = ("immobilize", ["immobil", "kneecap", "leg shot"]),
        ["sunder"] = ("armor-piercing", ["armor-pierc", "armor pierc", "penetrat", "body armor"]),
        ["weaken"] = ("suppression", ["suppress", "suppressing fire", "disarm"]),
        ["slow"] = ("injury", ["limp", "injur", "slow"]),
        ["curse"] = ("blackmail", ["blackmail", "dirt", "rumor", "compromat"]),
        ["hex"] = ("target mark", ["mark", "target", "laser"]),
        ["bind"] = ("handcuffs", ["handcuff", "grapple", "zip tie", "restrain"]),
        ["confuse"] = ("deception", ["decept", "distract", "bluff", "decoy"]),
        ["tome_arcane"] = ("analysis", ["analy", "evidence", "investigat", "inspect"]),
        ["tome_holy"] = ("coordination", ["coordinat", "team", "tactic"]),
        ["map"] = ("map", ["map", "route", "navigat", "scout"]),
        ["key"] = ("lockpicks", ["lockpick", "lock", "key", "door"]),
        ["gold"] = ("money", ["money", "bribe", "trade", "haggl"]),
        ["amulet"] = ("badge", ["badge", "talisman", "cross"]),
        ["vial"] = ("grenade", ["grenade", "bottle"]),
        ["potion_health"] = ("first aid kit", ["first aid"]),
        ["potion_mana"] = ("energy drink", ["energy drink", "coffee", "focus"]),
    };

    private static readonly Dictionary<string, (string Title, string[] Kw)> CyberEn = new(StringComparer.OrdinalIgnoreCase)
    {
        ["slash"] = ("blade strike", ["blade", "katana", "mantis", "monomolecular", "slash", "burst", "shot", "volley"]),
        ["fire"] = ("thermal damage", ["thermal", "napalm", "incendiar", "flamethrower", "plasma", "overheat"]),
        ["frost"] = ("cryo", ["cryo", "nitrogen", "cool"]),
        ["lightning"] = ("EMP and discharge", ["emp", "electromagnet", "discharge", "shocker", "taser", "pulse"]),
        ["wind"] = ("sonic wave", ["sonic", "sound", "acoust", "sonar", "ultrasound", "wave"]),
        ["earth"] = ("explosion", ["explos", "grenade", "rocket", "detonat", "mine", "blast"]),
        ["shadow"] = ("hacking", ["hack", "cyberattack", "neurohack", "code", "exploit", "daemon", "program", "quickhack", "breach"]),
        ["holy"] = ("laser", ["laser", "beam", "photon", "targeting beam"]),
        ["heal"] = ("nano-healing", ["nano", "medstim", "medkit", "regenerat", "medic", "heal"]),
        ["water"] = ("reboot", ["reboot", "purge", "reset", "defrag", "antivirus"]),
        ["revive"] = ("resuscitation", ["resuscit", "defibrill", "trauma", "back in action"]),
        ["barrier"] = ("force field", ["field", "force", "screen", "projector", "barrier", "shield"]),
        ["might"] = ("combat stim", ["stim", "adrenaline", "berserk", "overdrive", "muscle"]),
        ["haste"] = ("reflex booster", ["reflex", "booster", "sandevistan", "accelerat", "dash", "reaction"]),
        ["stealth"] = ("optical camo", ["camo", "chameleon", "invisib", "stealth", "disguise"]),
        ["guard"] = ("armoring", ["armor", "subdermal", "cover", "block", "taunt"]),
        ["poison"] = ("toxin", ["toxin", "neurotoxin", "chemical", "gas"]),
        ["bleed"] = ("bleeding", ["bleed", "blood", "wound", "rupture"]),
        ["burn"] = ("burning", ["burn", "arson", "ignite", "incendiar"]),
        ["stun"] = ("short circuit", ["short circuit", "stun", "concuss", "system failure"]),
        ["sleep"] = ("shutdown", ["shutdown", "switch off", "sedat", "sleep", "restart"]),
        ["fear"] = ("panic", ["panic", "fear", "intimidat", "alarm"]),
        ["blind"] = ("optics glitch", ["optic", "glare", "blind", "flash", "glitch"]),
        ["silence"] = ("jammer", ["jam", "signal suppress", "interference", "lockout"]),
        ["freeze"] = ("system freeze", ["freez", "hang", "stop"]),
        ["sunder"] = ("armor-piercing", ["armor-pierc", "armor pierc", "penetrat", "rupture"]),
        ["weaken"] = ("suppression", ["suppress", "suppressing fire", "weaken", "disarm"]),
        ["slow"] = ("overload", ["overload", "slow", "lag", "delay"]),
        ["curse"] = ("virus", ["virus", "worm", "trojan", "infect"]),
        ["hex"] = ("target mark", ["mark", "targeting", "marker", "highlight", "aim"]),
        ["bind"] = ("net and grapple", ["net", "grapple", "cyber-grip", "harpoon", "cable"]),
        ["confuse"] = ("navigation glitch", ["navigation", "disorient", "hologram", "decoy", "false target"]),
        ["tome_fire"] = ("chip: thermo", ["chip"]),
        ["tome_frost"] = ("chip: cryo", []),
        ["tome_nature"] = ("chip: bio", ["bio", "drone", "summon drone"]),
        ["tome_arcane"] = ("chip: analysis", ["scan", "analy", "recogni", "decrypt"]),
        ["tome_holy"] = ("chip: tactics", ["tactic", "sync", "team", "coordinat"]),
        ["tome_death"] = ("chip: elimination", ["eliminat", "execut", "finish off"]),
        ["scroll_blood"] = ("shard: red", []),
        ["scroll_water"] = ("shard: blue", ["shard"]),
        ["claw"] = ("mantis blades", ["mantis", "blades"]),
        ["horned_skull"] = ("trophy helmet", ["trophy"]),
        ["scales"] = ("armor plates", ["plate"]),
        ["herbs"] = ("biogel", ["biogel", "gel"]),
        ["mushroom"] = ("reagents", ["reagent", "chemical"]),
        ["vial"] = ("grenade", ["grenade", "bomb"]),
        ["ingot"] = ("scrap metal", ["scrap", "repair", "metal"]),
        ["fur"] = ("wires", ["wire", "cable"]),
        ["leather"] = ("polymer", ["polymer"]),
        ["rope"] = ("cable", ["tether"]),
        ["crystals"] = ("circuit board", ["board", "circuit"]),
        ["potion_health"] = ("medstim", ["medstim"]),
        ["potion_mana"] = ("RAM stim", ["ram", "memory", "deck cooling"]),
        ["potion_sun"] = ("combat stim", ["vigor"]),
        ["potion_poison"] = ("toxin ampoule", []),
        ["map"] = ("holomap", ["map", "recon", "scout drone", "trace"]),
        ["key"] = ("keycard", ["key", "lock", "door", "access"]),
        ["gold"] = ("eddies", ["eddies", "bribe", "deal", "trade"]),
        ["amulet"] = ("implant", ["implant", "cyber", "chrome"]),
    };

    /// <summary>Название клетки для модели и подсказок: английское в английском интерфейсе, иначе русское сеттинга.</summary>
    public static string TitleOf(Icon i) =>
        Lang.IsEn && MetaEn.TryGetValue(i.Id, out var en) ? en.Title
        : Meta.TryGetValue(i.Id, out var c) ? c.Title : i.Title;

    /// <summary>Все основы слов клетки: русские фэнтези + русские сеттинга + английские фэнтези + английские сеттинга.</summary>
    private static IEnumerable<string> WordsOf(Icon i)
    {
        IEnumerable<string> words = i.Kw;
        if (Meta.TryGetValue(i.Id, out var cy)) words = words.Concat(cy.Kw);
        if (FantasyEn.TryGetValue(i.Id, out var fe)) words = words.Concat(fe.Kw);
        if (!Genre.IsFantasy && MetaEn.TryGetValue(i.Id, out var ge)) words = words.Concat(ge.Kw);
        return words;
    }
}
