namespace RPG_Harness.Services;

/// <summary>
/// Английские тексты колеса дороги. Каталоги событий записаны по-русски (вместе с весами и местностями),
/// а в английском интерфейсе событие подменяется переводом по id: таблицы не размножаются, id остаются общими.
/// </summary>
public static partial class TravelEncounters
{
    private static readonly Dictionary<string, Encounter[]> EnCache = new();

    /// <summary>Каталог в английском переводе (события без перевода остаются как есть).</summary>
    private static Encounter[] Translated(Encounter[] source, Dictionary<string, (string T, string S, string C, string L)> en)
    {
        var key = Genre.Current + "/en";
        lock (EnCache)
        {
            if (EnCache.TryGetValue(key, out var cached)) return cached;
            var list = source.Select(e => en.TryGetValue(e.Id, out var t)
                ? e with { Title = t.T, Situation = t.S, Choice = t.C, LootHint = t.L }
                : e).ToArray();
            EnCache[key] = list;
            return list;
        }
    }

    private static readonly Dictionary<string, (string T, string S, string C, string L)> FantasyEn = new()
    {
        // ---------------- Minor ----------------
        ["abandoned-camp"] = ("Abandoned camp", "A cold fire pit, a torn awning, an overturned pot. The owners left in a hurry — or were taken.", "Look around (Perception/Survival DC 10–12) or walk on. The tracks may lead to a hook.", "a forgotten bag: supplies, a couple of coins, a personal item with a name"),
        ["lost-bundle"] = ("Dropped bundle", "By the roadside lies a bundle that fell off a cart: cloth tied with twine, something clinks inside.", "Keep it, leave it, or try to find the owner (somewhere ahead on the road).", "a petty merchant's goods or someone's parcel"),
        ["wayside-shrine"] = ("Wayside shrine", "A mossy idol of a local godling; at its foot — coppers, a ribbon, dried bread.", "Leave an offering (luck: advantage on one check until sunset) or take the gifts (a bad omen, the GM may bring it up later).", "a handful of coppers and a small charm"),
        ["ruined-watchtower"] = ("Ruined watchtower", "A half-collapsed tower by the road. The stairs hold; birds rustle at the top.", "Climb (Athletics DC 10, on a failure — a 1d4 bruise) — you can see the surroundings from there and maybe an old guard cache. Or walk on.", "a lookout's cache: a signal horn, a flint, a couple of coins"),
        ["dead-traveler"] = ("Dead traveler", "In the grass lies a long-dead wanderer. The clothes have rotted, an arrow shaft is in the back. A walking staff lies nearby.", "Search, bury (a good deed, a small reward from fate) or leave. The arrow is a hook: whose is it?", "a purse, travel gear, a letter or a marked map"),
        ["rotten-chest"] = ("Chest under the roots", "The roots of an old tree have wrapped around an iron-bound chest — someone buried it long ago, and the rains washed the earth away.", "Open it (Sleight of Hand DC 12 or by force — Athletics DC 13, noisy) or leave it.", "the cache contents: coins, a simple weapon or a trinket"),
        ["trapped-chest"] = ("Trapped chest", "A small chest sits too conveniently in a crevice. The lock gleams — new, unlike the chest itself.", "Spot the trap (Perception DC 13), disarm it (Sleight of Hand DC 13) or risk it: a poison needle, 1d6 and poisoned until a rest. Or don't touch it.", "a treasure hunter's bait — coins and one decent item"),
        ["broken-cart"] = ("Broken cart", "A merchant sits by a cart with a cracked axle, cursing at the horse. He is in a hurry to reach the fair.", "Help (Athletics or wits) — he will be grateful; or walk past, or haggle over the help.", "a discount with this merchant, a couple of coins or small goods"),
        ["lone-peddler"] = ("Peddler", "A lone peddler with a pack on his back: thread, spices, amulets \"against everything\", gossip.", "Trade (you can create a shop with set_merchant kind=general tier=village), ask about the road. He may also be a spy.", "purchases at his prices, a rumor about the road"),
        ["pilgrims"] = ("Pilgrims", "A group of pilgrims trudges toward a shrine, singing softly. They offer to share bread by the fire.", "Join them at the halt (rest, rumors, a blessing) or politely decline.", "food, a rumor, sometimes holy water or a charm"),
        ["wounded-beast"] = ("Wounded beast", "A young deer (or a dog, or a hawk) struggles in a poacher's snare.", "Free it (Animal Handling DC 11) — the beast may help later; kill it for meat and hide; leave.", "meat, a hide or nature's gratitude"),
        ["herb-glade"] = ("Herb glade", "A sunny glade: St. John's wort, burnet, something rare with silvery leaves.", "Gather (Nature/Medicine DC 11; on a failure — mistaken for a poisonous lookalike, poisoned) or walk on.", "herbs for potions, rarely a rare alchemical ingredient"),
        ["clear-spring"] = ("Clear spring", "An icy spring under a stone, the water is sweet. The place is clearly revered: colored ribbons all around.", "Rest and wash — a short rest without interruption; you can fill the flasks.", ""),
        ["old-well"] = ("Abandoned well", "By the ruins of a farmstead there is a well. Far below, something glints in the water.", "Climb down a rope (Athletics DC 12) or walk on. There may be more than a glint down there.", "a sunken wishing coin, a ring or a rusty key"),
        ["rotten-bridge"] = ("Rickety bridge", "A rope bridge over a ravine: the planks are rotten, the ropes creak.", "Cross carefully (Acrobatics DC 11, on a failure — a 1d6 fall and a lost item) or go around, losing half a day.", ""),
        ["bad-weather"] = ("Bad weather", "Downpour, hail or thick fog covers the road. Clothes are soaked, visibility is ten paces.", "Wait it out under cover (lost time) or press on (Survival DC 12, otherwise lose the way and get tired).", ""),
        ["big-tracks"] = ("Tracks of a big beast", "Fresh tracks, deep as if from a barrel. Bark torn off at a man's height.", "Go around, hide, or track it (Survival DC 13) — the beast's lair is near, and it may become a notable event.", "fur/a claw for an alchemist — if you track it and don't run into it"),
        ["hungry-bandits"] = ("Hungry bandits", "Three ragged men with clubs demand a \"toll\". It is clear they are more scared than the hero.", "Pay them off with a couple of coins, intimidate them (Intimidation DC 10), talk them down or drive them off by force — they will flee quickly.", "coppers, a dull knife, stolen goods"),
        ["small-barrow"] = ("Lonely barrow", "A low barrow with a toppled stone. Someone already started digging but gave up.", "Dig it up (noise, time; a risk of waking something or bringing a curse — Wisdom DC 12) or leave the dead in peace.", "an old coin, a bronze clasp, sometimes a rusty blade"),
        ["stray-messenger"] = ("Bird with a letter", "A carrier pigeon with a broken wing lands right at your feet. A sealed case is on its leg.", "Read it (the seal is broken — that will be noticed), deliver it to the addressee for a reward or let it go.", "the addressee's reward or valuable gossip"),
        ["smuggler-mark"] = ("Smugglers' mark", "A freshly carved sign on a roadside stone: a circle and three lines. Such signs mark caches.", "Search for the cache (Investigation DC 13) — the owners may return; or remember the sign.", "a cache: contraband (spices, tobacco, poisons) and coins"),
        ["shepherd"] = ("Shepherd by the fire", "An old shepherd warms himself by the fire, his dogs eye the hero. He knows every path and every legend of the area.", "Talk (rumors, a shortcut, a local legend about a treasure) or walk past.", "information, sometimes a piece of cheese and advice"),
        ["bird-nest"] = ("Rare bird's nest", "On a ledge — a firebreast's nest: alchemists pay silver for such eggs.", "Get it (Athletics DC 13; the parents attack — a couple of scratches) or leave it.", "eggs for an alchemist"),
        ["fox-thief"] = ("Thieving fox", "At night at the camp, a red fox drags off a bag of food — and something shiny from the pack.", "Chase it (Stealth/Survival DC 12) — the fox's den is full of other people's trinkets; or accept the loss.", "the fox's den: knick-knacks, beads, someone's lost earring"),
        ["fallen-tree"] = ("Blocked road", "A huge tree blocks the way. A cart's crushed chest is visible under the branches.", "Clear it (Athletics DC 14, takes long) or go around; under the trunk — the remains of someone's cargo.", "the surviving cargo"),
        ["lost-child"] = ("Lost child", "A girl of about seven cries by the road: she followed a goat and got lost.", "Take her home (the village is off the road — a detour) — the family will thank you as they can; or show her the way and move on.", "the village's gratitude: lodging, food, a family keepsake"),
        ["fairy-ring"] = ("Fairy ring", "A perfect circle of toadstools, the grass inside taller and greener. Quiet laughter can be heard.", "Step inside (Wisdom DC 13: success — a strange dream and a small fey gift; failure — an hour lost and one item gone) or go around.", "a fey trinket with a quirk"),
        ["hero-statue"] = ("Statue of a forgotten hero", "An ivy-covered statue of a warrior. The inscription on the pedestal is half-worn, but the name can be read.", "Clear the inscription (History DC 12) — knowledge of the world's past, a hook for an arc. Or walk on.", "information, sometimes a coin under the pedestal"),
        ["crossroads"] = ("Knocked-down signpost", "A crossroads, the signpost is knocked down and turned. The ruts go three ways.", "Get your bearings (Survival DC 12; on a failure — a day of travel wasted) or ask the locals.", ""),
        ["wandering-bard"] = ("Wandering bard", "A bard with a battered lute sings a ballad at the halt — it describes the place of a treasure suspiciously precisely.", "Listen and ask (a rumor about a treasure — a hook for the future), treat him, chase him off.", "a rumor about a cache; sometimes he sells a map for coins"),
        ["hunter-cairn"] = ("Hunters' cairn", "A stone cairn on the path: hunters leave supplies there for travelers. By custom — take one, leave one.", "Take something and leave something in return (luck) or take everything (the local hunters will become unfriendly).", "arrows, dried meat, a coil of rope"),
        ["dead-horse"] = ("Fallen horse", "A horse in rich harness lies by a stream. The saddle bears the brand of a noble house, the bags are torn off.", "Examine it (tracks: the rider was taken away), take the harness or inform the house (a reward, but also questions).", "an expensive saddle or harness, a heraldic buckle"),
        ["wild-bees"] = ("Wild hive", "A hollow hums: wild bees, honeycombs dripping with honey.", "Get the honey (Nature DC 12 with smoke; otherwise 1d4 stings) or go around.", "honey and wax — valued by herbalists"),
        ["poacher-trap"] = ("Poacher's trap", "Iron snaps under the leaves. A trap! (Perception DC 12, otherwise 1d6 damage and a limp until a rest.)", "Get free, find other traps and the poacher's cache, or leave.", "the poacher's hides and gear"),
        ["abandoned-hut"] = ("Empty hut", "A forester's hut: the door is unlocked, a bowl of dried porridge on the table, a diary on the shelf.", "Spend the night (rest), read the diary (the last entry is alarming — a hook) or leave.", "a diary, tools, a supply of firewood and food"),
        ["desert-mirage"] = ("Mirage", "On the horizon — an oasis with palm trees. It hasn't come any closer for an hour.", "Don't give in (Wisdom DC 12; on a failure — a detour and extra thirst) or go toward the mirage — sometimes there really is a well under it.", ""),
        ["shipwreck-flotsam"] = ("Washed-up cargo", "The waves have thrown wreckage and a barrel with a trading house's seal onto the shore.", "Open the barrel, search the wreckage, return the seal to the trading house for a reward.", "wine, spices or cloth; rarely a small casket"),
        ["ice-crevice"] = ("Frozen find", "A man in ancient armor is frozen into the clear wall of a glacier, his hand clutching something.", "Cut him out (long, noisy, Athletics DC 13) or walk on. The ice may keep more than a dead man.", "an ancient item in good condition"),
        ["quagmire"] = ("Quagmire", "A tussock sinks underfoot. The bog grabs you by the knees (Athletics DC 12, on a failure — lose an item from the bag or sink waist-deep).", "Get out, save your things; a strap of someone's bag sticks out of the bog.", "the bag of a vanished traveler"),
        ["will-o-wisp"] = ("Will-o'-the-wisps", "Blue lights dance in the fog and call with the voices of people you know.", "Don't follow (Wisdom DC 13) or follow — the lights lead into the bog, but sometimes to a barrow with drowned men's treasure.", "the drowned men's treasure, if you get out"),
        ["toll-patrol"] = ("Road patrol", "A guard patrol: checking travel papers, a toll, questions — \"who, where, why\".", "Pay, negotiate (Persuasion), deceive (Deception DC 13) or go around. The patrol shares news.", "news and rumors; in a conflict — trouble"),
        ["wolf-for-farmers"] = ("Wolf at the farmstead", "The farmers ask you to drive off a wolf that kills their sheep. They offer what they can.", "Take it on (a short hunt, a light fight with one or two wolves) or refuse.", "the farmers' pay, a wolf hide"),
        ["goblin-scavengers"] = ("Goblin scavengers", "Two or three goblins rummage through a wrecked cart and argue. They haven't noticed the hero yet.", "Go around, chase them off, sneak up and eavesdrop (they have news) or haggle — they will sell their finds.", "their finds: a rusty dagger, a flask, shiny buttons"),
        ["mountain-goat"] = ("Mountain goat", "A stubborn giant goat blocks a narrow path above a precipice and has no intention of giving way.", "Wait, lure it with food, scare it off (Intimidation/Animal Handling DC 12) or climb around (Athletics DC 13).", ""),
        ["roadside-graveyard"] = ("Roadside graveyard", "Twilight, crooked crosses, a scraping sound from under one of them.", "Check it (a lone ghoul or just a scavenging badger), go around or say a prayer.", "offerings on the graves (taking them is wrong), the ghoul's belongings"),
        ["herbalist-hermit"] = ("Herbalist on the road", "A hunched herbalist gathers roots and grumbles. Her basket is full.", "Help carry it (gratitude — a potion), trade, ask about the poisons and ailments of the region.", "a simple healing potion or an herb"),
        ["lost-mule"] = ("Stray mule", "A loaded mule peacefully chews grass by the road. The owner is nowhere to be seen.", "Take the mule with the load, look for the owner or let it go. The owner may show up and accuse you of theft.", "the load: tools, cloth, supplies"),
        ["ancient-milestone"] = ("Ancient milestone", "A stone with an inscription in a dead language. Under it — a recess covered with a slab.", "Read it (History/Arcana DC 13), lift the slab (Athletics DC 12) or move on.", "an old coin or a piece of an ancient map"),
        ["stargazing"] = ("Starry night", "A clear night, a meteor shower. The guide (or the hero) notices a strange constellation.", "Look closely (Arcana/Religion DC 12) — an omen, a hint of what is to come; or just get some sleep.", ""),
        ["fellow-traveler"] = ("Fellow traveler", "A lone traveler asks to walk together: it's safer in pairs.", "Accept (he is talkative and knows rumors; he may have his own secrets) or refuse.", ""),

        // ---------------- Notable ----------------
        ["bandit-ambush"] = ("Bandit ambush", "At a narrow spot a log blocks the road; 4–6 bandits with a leader step out from the trees.", "Give up some goods, haggle, bluff, flee (Athletics/Acrobatics DC 13) or fight. The leader respects strength.", "loot from the leader: a better weapon, a purse, goods stolen from earlier victims"),
        ["beast-den"] = ("Beast's den", "A cave by a stream, the entrance littered with bones. A musky smell comes from inside — a bear, a she-wolf with cubs or something worse.", "Go around, lure it out, sneak up or fight. Deep inside — the belongings of earlier victims.", "belongings of vanished travelers, the beast's trophies"),
        ["smuggler-cave"] = ("Smugglers' cave", "An inconspicuous grotto, fresh barrel tracks. Inside — a storehouse and a couple of guards, and a tripwire with a bell at the entrance.", "Slip through (Stealth DC 13), negotiate, report to the guard (a reward) or clean it out.", "contraband, money, sometimes forbidden alchemical goods"),
        ["caravan-attack"] = ("Caravan in trouble", "Shouts ahead: a trade caravan has been attacked (wolves, bandits or raiders of a hostile faction).", "Intervene (a fight, saving people), help after the fight or go around. The caravan master will remember.", "the caravan master's reward, discounts at his trading house, connections"),
        ["haunted-chapel"] = ("Haunted chapel", "A ruined chapel; at night the ghost of a nun who was never given her last rites weeps in it.", "Learn her story and lay her to rest (Religion DC 13 + a small task), banish her by force or leave before nightfall.", "a blessed item or a relic of the chapel"),
        ["knight-tomb"] = ("Knight's tomb", "A stone crypt in a hill: steps down, a couple of traps and 1–3 restless dead.", "Go down and loot it (or pay respects), block the entrance, leave. The dead respect those who don't loot.", "the fallen knight's sword or armor"),
        ["witch-hut"] = ("Witch's hut", "A hut on stilts, green smoke from the chimney. The mistress knows who has come before the knock.", "A deal: a service for a potion, lift/lay a curse, knowledge. You can refuse — she will remember.", "a potion, a charm or secret knowledge — by the deal"),
        ["bounty-hunters"] = ("Bounty hunters", "Three mercenaries with a wanted poster: they are looking for a man who looks a lot like the hero.", "Prove it's a mistake, pay them off, flee, fight — or find out who actually posted the bounty.", "the mercenaries' gear, the poster as a hook"),
        ["bridge-troll"] = ("Troll under the bridge", "A stone bridge; a troll lives under it and demands a toll: gold, a riddle or something tasty.", "Pay, ask a riddle (Intelligence DC 13), trick it, find a ford (time) or fight (dangerous).", "the \"tolls\" of previous travelers the troll has hoarded"),
        ["hermit-mage"] = ("Hermit mage", "A lonely little tower in the wilderness; its master is an old mage, gone feral and suspicious.", "Pass his test (a riddle, a service), bargain for knowledge or leave. He may teach a spell.", "a scroll, a magical trinket or training"),
        ["old-battlefield"] = ("Old battlefield", "A field of rusty iron, barrows of the fallen. At night a cold light smolders above it.", "Search for intact weapons by day (Perception DC 13), avoid staying the night — or stay and meet the ghosts.", "an intact weapon or a banner with a history"),
        ["nomad-camp"] = ("Nomad camp", "The tents of a nomadic tribe (orcs, steppe folk, centaurs). The warriors have already noticed the hero.", "Come in peace (Persuasion, gifts), trade, go around. Insulting them means making enemies.", "trade, a guide, possibly an ally"),
        ["star-stone"] = ("Fallen star", "At night something flared in the hills — in the morning there is a smoking crater with a glowing stone. Others are already heading for it.", "Get there first (a race), negotiate with the rivals or back off.", "star metal — valued by smiths and mages"),
        ["old-mine"] = ("Abandoned mine", "An adit with rotten supports; deep inside — a vein and someone's lair (kobolds, spiders).", "Explore (cave-ins, traps, inhabitants), take ore at the entrance or leave.", "ore, gems, prospectors' tools"),
        ["caged-prisoner"] = ("Prisoner in a cage", "In a clearing — a cage with a beaten prisoner inside, begging for help. Looks like bait.", "Free him (lock DC 13; an ambush nearby?), question him from a distance or leave. The prisoner may become an ally — or betray you.", "the prisoner's gratitude: information, connections, sometimes an item from a cache"),
        ["honor-duel"] = ("Knight at the bridge", "A knight-errant has sworn to let no one pass who doesn't cross swords with him.", "Accept the duel (to first blood), talk him out of it (Persuasion DC 14), find another way.", "the knight's respect and his gift, or his horse/shield on a victory"),
        ["wishing-well"] = ("Wishing well", "A stone well whispers: \"Throw a coin — and ask.\" Around it are the bones of those who asked too much.", "Throw a coin (Wisdom DC 14: a small piece of luck or a catch), leave, try to unravel the curse.", "a small blessing or a curse — by the roll"),
        ["harpy-nest"] = ("Harpy nest", "Harpies circle above the pass; their song pulls toward the cliff (Wisdom DC 13).", "Slip past (Stealth/speed), fight, plug your ears with wax. In the nest — the belongings of travelers who fell.", "belongings of fallen travelers"),
        ["shallow-wreck"] = ("Ship aground", "A wrecked ship lies on a shoal. In the hold — water and crabs the size of a man.", "Search it (dangerous: tides, creatures), sell the location of the find, leave.", "the ship's cash box, a navigation instrument, cargo"),
        ["oasis-djinn"] = ("Oasis with a cunning spirit", "An oasis; a small fire spirit lives in the palms and adores deals with a catch.", "Play with it (riddles, a wager), ask for water, drive it off (dangerous).", "the spirit's gift: a fire amulet or a supply of water"),
        ["bog-hag"] = ("Bog hag", "An old woman calls you onto the causeway: \"Help granny, dearie.\" The fog thickens.", "See through her (Insight DC 14), strike a bargain, flee or fight.", "the hag's vials, an enchanted doll"),
        ["fog-village"] = ("Village in the fog", "A village that isn't on any map emerges from the fog. The people are welcoming, but time flows differently here.", "Stay as a guest (a day turns into a week or the other way round), solve the mystery, leave before sunset.", "the villagers' gift — if you solve the mystery"),
        ["deserters"] = ("Deserters", "A band of deserters with their loot. Tired, angry, afraid of pursuit.", "Negotiate (they will pay well for silence), turn them in to the authorities, fight.", "the loot: weapons, coins, other people's valuables"),
        ["cult-ritual"] = ("Cultist ritual", "At night in a grove — torches, chanting, a bound man on a stone.", "Disrupt the ritual (a fight or a trick), follow the cult (a hook), leave.", "cult relics, notes with names"),
        ["strange-circus"] = ("Traveling circus", "Gaudy wagons, clowns with frozen smiles. They invite you to a show.", "Watch (games of chance, prizes), snoop around (what's in the cage isn't an animal), leave.", "winnings, a curiosity, a rescued creature"),
        ["werewolf-moon"] = ("Full moon", "Howling from all sides. The tracks show wolves the size of a calf, and one set of tracks suddenly becomes human.", "Take cover until morning, track the werewolf (a hook), fight (risk of contracting lycanthropy).", "a hunter's silver dagger, a trophy"),
        ["myconid-grotto"] = ("Grotto of the mushroom folk", "The cave glows softly, myconids communicate with spores. Peaceful if you don't trample them.", "Trade spores and knowledge, pass through (a shortcut), frighten them.", "rare mushrooms and spores for alchemy"),
        ["gate-golem"] = ("Guardian of the ancient gate", "A stone golem at an overgrown gate; according to the inscription, it lets through those who name the word.", "Find the word (History/Arcana DC 14), go around, fight (it is strong). Beyond the gate — small ruins.", "finds from the small ruins"),
        ["crossroads-fair"] = ("Crossroads fair", "A spontaneous fair at a crossroads: merchants, fistfights, a shooting contest for a prize.", "Trade (you can create 1–2 shops), take part in a contest (Athletics/shooting) — the prize is good.", "the contest prize, rare goods from the merchants"),
        ["dying-courier"] = ("Wounded courier", "A rider falls from his horse at the hero's feet: arrows in his back, a dispatch for an important person in his hand.", "Deliver it (a reward and a plot twist), read it, hide it. Assassins are following the courier.", "the addressee's reward, patronage"),
        ["sand-worm-tracks"] = ("Sandstorm", "A storm blots out the sky; something big moves through the sand underfoot.", "Take cover (Survival DC 14), run for the rocks; after the storm, buried ruins are uncovered.", "finds from the ruins uncovered by the storm"),
        ["ice-wolves"] = ("Pack of ice wolves", "White wolves have been following for three days, waiting for the traveler to weaken.", "Scare them off with fire, fight the leader, confuse the trail (Survival DC 14).", "the leader's hide — valuable"),

        // ---------------- Major ----------------
        ["ancestral-crypt"] = ("Crypt of an ancient family", "The family crypt of an extinct line: 3–4 halls, mechanical traps, undead and a knight guardian in the last hall.", "You can scout and retreat at any moment except in the last hall (the door locks). You can also not enter at all.", "the family heirloom and the crypt's treasury"),
        ["young-dragon"] = ("Young dragon's lair", "Charred trees, scorched earth, the smell of sulfur. A young dragon sleeps on a pile of coins.", "Sneak in and carry off one thing (Stealth DC 16), negotiate (dragons are vain), leave — or fight (very dangerous).", "the dragon's hoard"),
        ["wizard-tower-ruins"] = ("Ruins of a wizard's tower", "A half-ruined tower where the guarding spells still work: illusions, golems, locked doors with key words.", "Explore floor by floor (you can retreat between floors), leave. Wits beat brute force here.", "scrolls, a staff or a wand, a spellbook"),
        ["bandit-fortress"] = ("Bandit baron's fortress", "A former fort on a cliff, 15–20 bandits, a self-proclaimed baron and prisoners in the cellar.", "Assault (nearly suicide alone), infiltration, negotiation, hiring allies in the nearest town. Or go around.", "the baron's treasury, freed prisoners (connections), captured weapons"),
        ["forgotten-temple"] = ("Temple of a forgotten god", "A temple swallowed by jungle or sand. Trials of faith, mummy priests, an altar that still answers.", "Pass the trials (mind, spirit, strength), desecrate it (the god's wrath) or leave.", "a sacred artifact or a god's gift"),
        ["giant-lair"] = ("Giant's lair", "The hill turns out to be a giant's hut. Inside — captive peasants, fattened for a feast.", "Rescue the captives by cunning, negotiate (giants love wagers and games), fight (very dangerous), leave.", "the giant's sack: strange finds and treasures"),
        ["fey-gate"] = ("Gate to the fey realm", "A stone arch in a ring of birches glows at dawn. Beyond it — the court of the fey queen.", "Enter (bargaining, dangerous deals, time flows differently), refuse — the arch will close forever.", "a fey gift with a condition"),
        ["warlord-tomb"] = ("Warlord's tomb", "The barrow of a great warlord; the ghost guards of his retinue test the worth of whoever enters.", "Pass the trial of honor (no looting), fight the retinue, leave.", "the warlord's weapon or armor"),
        ["hunting-manticore"] = ("Manticore on the hunt", "A manticore has chosen the hero as prey and has been stalking them for two days, shooting spikes.", "Find the lair and strike first, set an ambush, retreat to a town, negotiate (it is intelligent and vain).", "the contents of the lair, spike venom"),
        ["pirate-cove"] = ("Pirate cove", "A cove with a ship under a black flag; in the caves — a loot store and a tavern for their own.", "Infiltrate, trade with the pirates, turn them in to the navy, rob the store, pass by.", "pirate loot, a treasure map"),
        ["dwarven-forge"] = ("Forge of the ancient dwarves", "An abandoned underground workshop: the mechanisms still work, automaton guards walk in circles.", "Figure out the mechanisms (Intelligence/tools), sneak, fight, leave.", "dwarven armor or weapons, blueprints"),
        ["sand-necropolis"] = ("Sand necropolis", "A storm has uncovered a city of the dead: stepped tombs, scorpion guards, a curse on the treasures.", "Explore until the next storm (a timer!), take a little and leave, don't enter.", "pharaohs' gold, a cursed amulet"),
        ["drowned-city"] = ("Drowned city", "Under the lake's water — the spires of an old city. A drought has exposed the dome of a temple.", "Dive (breath, water creatures), find an air pocket, leave.", "the treasures of the drowned temple"),
        ["ice-citadel"] = ("Ice citadel", "In the ice — the citadel of the winter witch, her snow servants and frozen prisoners.", "Infiltrate, bargain for passage, melt it (fire is the key), leave.", "a winter artifact, freed prisoners"),
        ["salamander-forge"] = ("Volcanic forge", "A salamander forge in a volcano's crater: they forge for whoever brings a rare metal.", "A deal (commission a weapon), theft, a fight in the heat (exhaustion), leave.", "a commissioned fire weapon"),
        ["maze-forest"] = ("Labyrinth forest", "The paths weave into a ring; the master of the forest, an ancient spirit, is playing with the traveler.", "Work out the rules of the game (Wisdom/Survival DC 15), bargain for a way out, burn it (the forest's wrath).", "a gift from the master of the forest"),

        // ---------------- Legendary ----------------
        ["fallen-empire-vault"] = ("Vault of a fallen empire", "A multi-level vault of a vanished empire: elite construct guards, deadly traps, seals. On the lowest level — the relic of the emperors.", "Descend level by level (between levels you can leave and come back with allies), retreat, sell information about the entrance.", "the empire's legendary relic and the level's treasury"),
        ["ancient-dragon"] = ("Sleeping ancient dragon", "The mountain is an ancient dragon's lair. It has slept for centuries; the hoard is the size of a cathedral.", "Steal one item (Stealth DC 18), wake it and talk (deadly dangerous, but dragons value courtesy), leave.", "one legendary item from the hoard"),
        ["sword-in-stone"] = ("Sword in the stone", "On an island in the middle of a lake — a stone with a blade. A ghost guardian asks: \"Why do you need the sword?\"", "Pass the trial of worth (an answer + a deed), fight the guardian, leave.", "a legendary blade (only for the worthy)"),
        ["sky-ruin"] = ("Fallen sky island", "A sky island has crashed into the valley: the ruins of a flying city, the enchantments still work, gravity misbehaves.", "Explore (dangerous, rival looters are already on their way), take a little, leave.", "an artifact of the sky people"),
        ["lich-tomb"] = ("Tomb of the lich king", "The crypt of a king who became a lich. His phylactery and staff lie in a hall the lich guards himself.", "Scout and leave (the information is valuable), prepare (allies, consecrated weapons), storm it. Without a plan — death.", "the lich's legendary staff; a destroyed phylactery — glory"),
        ["god-forge"] = ("Forge of a god", "The cold forge of a smith god: the hammer is still warm. The fire can be lit if a sacrifice is made.", "Light it (a price!), forge one item, leave. The god may notice.", "a legendary item forged by the hero"),
        ["precursor-ark"] = ("Ark of the precursors", "Underground — the ark of an ancient race: mechanisms, guardians, knowledge capable of changing the world.", "Get in (riddles, guardians), take knowledge or an item, seal it, leave.", "a legendary precursor artifact"),
        ["world-tree-heart"] = ("Heart of the ancient forest", "A tree older than kingdoms. An ent guardian asks why the traveler has come.", "Help the forest (a quest), ask for a gift, try to take it by force (the wrath of the whole forest).", "the forest's legendary gift: a bow, a staff or a seed"),
        ["ghost-ship"] = ("Ghost ship", "In the fog — the ghost ship of a legendary captain. The crew invites you aboard.", "Play with the captain (dice, riddles), free the crew from the curse, flee.", "the captain's legendary blade or compass"),
        ["demon-gate"] = ("Gates of the underworld", "A rift reeking of sulfur; at the gates lies the weapon of an ancient hero who fell sealing them.", "Take the weapon (demon guards, the seal will weaken), strengthen the seal, leave.", "the fallen hero's legendary weapon"),
    };
}
